### ISSUE TITLE
is ReLU needed after conv_ul?

### ISSUE THREAD

**Issue by realwill** [katotetsuro/chainer-maskrcnn#7]
and conv_bl, conv_ur, conv_br is not followed ReLU yet, is ReLU is needed after the new conv layers?

**Comment by katotetsuro** [comment]
I have same question, but couldn't read from paper.
I think accuracy will slightly improve by using relu.

**Comment by realwill** [comment]
@katotetsuro that is my question, there is no relu from paper, but some reimplement as https://github.com/msracver/Deformable-ConvNets/pull/119/commits/0b566954806659033b83ad0cfcdca6cf58c10a81   add relu after every conv

**Comment by katotetsuro** [comment]
>I have same question

I mean I don't know which is correct.
But I think MSRA's way is better 😄
